# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: myselforg5
# "service" is the name of this project. This will also be added to your AWS resource names.
app: todo-app
service: TodoApp
plugins:
  - serverless-offline
frameworkVersion: "4"
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  deploymentMethod: direct
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
