# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: myselforg5
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverlessCheck
plugins:
  - serverless-offline
frameworkVersion: "4"
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  deploymentMethod: direct
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  httpApi:
    cors: true
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  sai:
    handler: handler.sai
    events:
      - httpApi:
          path: /sai
          method: get
